# Generated by Django 5.2.15 on 2026-06-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_emailopenevent_city_emailopenevent_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailopenevent',
            name='is_prefetch',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
